spring:
  couchbase:
    bootstrap-hosts: couchbase
    env:
      timeouts:
        connect: 100000
        socket-connect: 100000
    bucket:
      name: todolist
      password: password
  data:
    couchbase:
      auto-index: true
logging:
  level: debug

---

spring:
  profiles: local
  couchbase:
    bootstrap-hosts: 192.168.99.101:11211